Description: >
  This is the basic EC2 instance cfn template.
  It will take the parameters below manually as input to create the EC2 instance:
   - AMI id // Automatically selected based on the OS requirement in the input parameter.
   - KeyPair Name // Retrieved from Parameter Store based on the input.
   - Instance Type // Selected based on the pre-defined size of the environment.
   - SecurityGroupID // Refer to security group stack output to get the input.
   - SubnetID // Refer to vpc stack output to get the input. 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Instance Environment Settings
      Parameters:
      - LatestAmiId
      - KeyName
      - EnvironmentSize
      - EnvironmentType    
    - Label:
        default: VPC Networking Settings
      Parameters:
      - VpcStackName
      - MySubnetID
      - PublicIp
    - Label:
        default: Domain Settings
      Parameters:
      - ADDirectoryId
      - ADDirectoryName
      - ADDnsIpAddress1
      - ADDnsIpAddress2  

    ParameterLabels:
      LatestAmiId:
        default: Windows Server 2019 AMI Id      
      KeyName:
        default: Key Name to be used 
      EnvironmentSize:
        default: Environment Size
      EnvironmentType:
        default: Environment Type
      VpcStackName:
        default: VPC Stack Name
      MySubnetID:
        default: Subnet ID 
      PublicIp:
        default: Enable Public IP 
      ADDirectoryId:
        default: Active Directory Id 
      ADDirectoryName:
        default: Active Directory Name 
      ADDnsIpAddress1:
        default: Active Directory DNS 1
      ADDnsIpAddress2:
        default: Active Directory DNS 2

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base'

  KeyName :
    Type : 'AWS::SSM::Parameter::Value<AWS::EC2::KeyPair::KeyName>'
    Default: myEC2Key

  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)

  EnvironmentType:
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Production
    Description: Select Environment Type (Production or Development)  

  PublicIp:
    Type: String
    Default: Enable
    AllowedValues:
      - Enable
      - Disable
    Description: Choose Enable to provide public IP address for the instance, otherwise, choose Disable.

  MySubnetID:  
    Description: Please enter the subnetID this EC2 instance will be deployed into.
    Type: AWS::EC2::Subnet::Id

  # VpcStackName created from 01.vpc_01.yaml. This value is used to retrieve output values from vpc template.
  VpcStackName:
    Description: Name of VPC stack. It must be match with the target VPC.
    Type: String
    Default: myVPC
    ConstraintDescription: VPC name must match with the target VPC.

  ADDirectoryId:
    Type: String
    Description: Active DirectoryId. Eg. d-12345679a
  ADDirectoryName:
    Type: String
    Description: Active Directory Name. Eg. my.ad.com
  ADDnsIpAddress1:
    Type: String
    Description: Active Directory DNS 1. Eg. 10.0.0.142
  ADDnsIpAddress2:
    Type: String
    Description: Active Directory DNS 2. Eg. 10.0.0.143  

Mappings:

  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
    LARGE:
      "EC2" : "t2.medium"
  InternetAccess:
    Enable:
      "IPv4" : "true"
    Disable:
      "IPv4" : "false"  

Resources:
  
  RootRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "root"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles: 
        - Ref: "RootRole"
  RootInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - Ref: "RootRole"

  MySsmDocument:
    Type: 'AWS::SSM::Document'
    Properties:
      Content:
        schemaVersion: '1.2'
        description: Join instances to an AWS Directory Service domain.
        parameters:
          directoryId:
            type: String
            description: (Required) The ID of the AWS Directory Service directory.
          directoryName:
            type: String
            description: >-
              (Required) The name of the directory; for example,
              test.example.com
          dnsIpAddresses:
            type: StringList
            default: []
            description: >-
              (Optional) The IP addresses of the DNS servers in the directory.
              Required when DHCP is not configured. Learn more at
              http://docs.aws.amazon.com/directoryservice/latest/simple-ad/join_get_dns_addresses.html
            allowedPattern: >-
              ((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)
        runtimeConfig:
          'aws:domainJoin':
            properties:
              directoryId: '{{ directoryId }}'
              directoryName: '{{ directoryName }}'
              dnsIpAddresses: '{{ dnsIpAddresses }}'

  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      KeyName : !Ref KeyName
      NetworkInterfaces: 
        - AssociatePublicIpAddress: !FindInMap [InternetAccess, !Ref PublicIp, IPv4]
          DeviceIndex: "0"
          GroupSet: 
            - !ImportValue 
               'Fn::Sub': '${VpcStackName}-sharedinf-webdmzid'
            
          SubnetId: !Ref MySubnetID
      IamInstanceProfile: !Ref RootInstanceProfile
      SsmAssociations:
        - DocumentName: !Ref MySsmDocument
          AssociationParameters:
            - Key: directoryId
              Value:
                - !Ref ADDirectoryId
            - Key: directoryName
              Value:
                - !Ref ADDirectoryName
            - Key: dnsIpAddresses
              Value:
                - !Ref ADDnsIpAddress1
                - !Ref ADDnsIpAddress2
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}  
        - Key: Team   
          Value: !Ref EnvironmentType