Description: >
  This is the basic Network Access Control List (NetworkACL) template. 
  It will take the input values: VPCid, publicsubnets from vpc_1 template.
  There is 01 NetworkACL will be created: WebDMZ-ACL.
  WebDMZ-ACL: will associate with 2 public subnets and define some allow/deny rules as example for traffic coming in and going out from/to Internet.
  
Parameters:
  VpcStackName:
    Description: Name of VPC stack. It must be match with the target VPC.
    Type: String
    ConstraintDescription: VPC name must match with the target VPC.

Resources:

  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub ${VpcStackName} WebDMZ-ACL
      VpcId: !ImportValue 
        'Fn::Sub': '${VpcStackName}-sharedinf-vpcid'

  PublicSubnetAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !ImportValue 
        'Fn::Sub': '${VpcStackName}-sharedinf-publicsubnets'
      NetworkAclId:
        Ref: PublicNetworkAcl  

  InboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
        NetworkAclId:
          Ref: PublicNetworkAcl
        RuleNumber: 100
        Protocol: 6
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 22
          To: 22
  OutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: PublicNetworkAcl
      RuleNumber: 100
      Protocol: -1
      Egress: true
      RuleAction: allow
      CidrBlock: 0.0.0.0/0  

Outputs:
  PublicNetworkAcl:
    Description: A reference to the created NetworkAcl
    Value: !Ref PublicNetworkAcl
    Export: # added to export
      Name: !Sub ${VpcStackName}-sharedinf-publicnetworkacl          