Description: >
  This is the basic Network Access Control List (NetworkACL) template. 
  It will take the input values: VPCid, publicsubnets from vpc_1 template.
  There is 01 NetworkACL will be created: WebDMZ-ACL.
  WebDMZ-ACL: will associate with 2 public subnets and define 2 ingress rules: 
  1. allow SSH and http/https from internet (igress).
  2. allow all traffic going out to the Internet (egress)
  
Parameters:
  VpcStackName:
    Description: Name of VPC stack. It must be match with the target VPC.
    Type: String
    ConstraintDescription: VPC name must match with the target VPC.

Resources:

  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub ${VpcStackName} WebDMZ-ACL
      VpcId: !ImportValue 
        'Fn::Sub': '${VpcStackName}-sharedinf-vpcid'

  PublicSubnet1AclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !ImportValue 
        'Fn::Sub': '${VpcStackName}-sharedinf-publicsubnet1'
      NetworkAclId:
        Ref: PublicNetworkAcl  

  PublicSubnet2AclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !ImportValue 
        'Fn::Sub': '${VpcStackName}-sharedinf-publicsubnet2'
      NetworkAclId:
        Ref: PublicNetworkAcl  

  InboundRule100:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
        NetworkAclId:
          Ref: PublicNetworkAcl
        RuleNumber: 100
        Protocol: 6
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 22
          To: 22

  InboundRule200:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
        NetworkAclId:
          Ref: PublicNetworkAcl
        RuleNumber: 200
        Protocol: 6
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 80
          To: 80
  InboundRule300:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
        NetworkAclId:
          Ref: PublicNetworkAcl
        RuleNumber: 300
        Protocol: 6
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 443
          To: 443

  OutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: PublicNetworkAcl
      RuleNumber: 100
      Protocol: -1
      Egress: true
      RuleAction: allow
      CidrBlock: 0.0.0.0/0  

Outputs:
  PublicNetworkAcl:
    Description: A reference to the created NetworkAcl
    Value: !Ref PublicNetworkAcl
    Export: # added to export
      Name: !Sub ${VpcStackName}-sharedinf-publicnetworkacl          